#!/usr/bin/env python3
"""
Add PDF Form JavaScript Actions
Enhances a PDF generated by pdf-lib with JavaScript validation/formatting actions.

Install dependencies:
    pip3 install pikepdf

Usage:
    python3 add-form-javascript.py input.pdf output.pdf
"""

import sys
import pikepdf
from pikepdf import Dictionary, Name, String, Array

def add_special_format(field, format_type):
    """
    Add AFSpecial_Format action to a field.
    format_type: 0=zipcode, 1=zipcode+4, 2=phone, 3=ssn
    """
    js_code = f"AFSpecial_Format({format_type});"
    
    if '/AA' not in field:
        field['/AA'] = Dictionary()
    
    field['/AA']['/F'] = Dictionary({
        '/S': Name('/JavaScript'),
        '/JS': String(js_code)
    })

def add_range_validation(field, min_val, max_val):
    """
    Add AFRange_Validate action to a field.
    """
    js_code = f"AFRange_Validate(true, {min_val}, true, {max_val});"
    
    if '/AA' not in field:
        field['/AA'] = Dictionary()
    
    field['/AA']['/V'] = Dictionary({
        '/S': Name('/JavaScript'),
        '/JS': String(js_code)
    })

def add_number_format(field, decimals=2, sep_style=0, neg_style=0, currency='$', prepend=True):
    """
    Add AFNumber_Format action to a field.
    """
    prepend_int = 1 if prepend else 0
    js_code = f'AFNumber_Format({decimals}, {sep_style}, {neg_style}, 0, "{currency}", {prepend_int});'
    
    if '/AA' not in field:
        field['/AA'] = Dictionary()
    
    field['/AA']['/F'] = Dictionary({
        '/S': Name('/JavaScript'),
        '/JS': String(js_code)
    })

def add_date_format(field, date_format="mm/dd/yyyy"):
    """
    Add AFDate_FormatEx action to a field.
    """
    js_code = f'AFDate_FormatEx("{date_format}");'
    
    if '/AA' not in field:
        field['/AA'] = Dictionary()
    
    field['/AA']['/F'] = Dictionary({
        '/S': Name('/JavaScript'),
        '/JS': String(js_code)
    })
    
    # Also add keystroke validation
    keystroke_code = f'AFDate_KeystrokeEx("{date_format}");'
    field['/AA']['/K'] = Dictionary({
        '/S': Name('/JavaScript'),
        '/JS': String(keystroke_code)
    })

def find_field_by_name(pdf, field_name):
    """
    Find a form field by name in the PDF.
    """
    if '/AcroForm' not in pdf.Root:
        return None
    
    acroform = pdf.Root['/AcroForm']
    if '/Fields' not in acroform:
        return None
    
    for field in acroform['/Fields']:
        if '/T' in field and str(field['/T']) == field_name:
            return field
        # Check for nested fields
        if '/Kids' in field:
            for kid in field['/Kids']:
                if '/T' in kid and str(kid['/T']) == field_name:
                    return kid
    
    return None

def enhance_pdf_forms(input_path, output_path):
    """
    Enhance the demo PDF with JavaScript form actions.
    """
    print(f"📄 Opening {input_path}...")
    pdf = pikepdf.Pdf.open(input_path)
    
    print("🔧 Adding JavaScript actions to form fields...")
    
    # Phone field - AFSpecial_Format(2) for phone
    phone_field = find_field_by_name(pdf, 'phone')
    if phone_field:
        print("  ✓ Adding phone formatter to 'phone' field")
        add_special_format(phone_field, 2)
    
    # Email field - already has required flag, add pattern validation
    email_field = find_field_by_name(pdf, 'email')
    if email_field:
        print("  ✓ Email field already has required flag (from pdf-lib)")
    
    # Username - already has maxLength from pdf-lib
    username_field = find_field_by_name(pdf, 'username')
    if username_field:
        print("  ✓ Username field already has maxLength (from pdf-lib)")
    
    # Save enhanced PDF
    print(f"💾 Saving enhanced PDF to {output_path}...")
    pdf.save(output_path)
    print("✅ Done! The PDF now has JavaScript form actions.")
    print("")
    print("📋 Added features:")
    print("  • Phone field: Auto-format to (xxx) xxx-xxxx")
    print("")
    print("🧪 Test with: allowFormJavaScript: true in PDFRenderer config")

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print("Usage: python3 add-form-javascript.py input.pdf output.pdf")
        print("")
        print("Example:")
        print("  python3 add-form-javascript.py public/sample.pdf public/sample-enhanced.pdf")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    
    try:
        enhance_pdf_forms(input_file, output_file)
    except Exception as e:
        print(f"❌ Error: {e}")
        sys.exit(1)
